name: Monorepo Deploy to ECS

on:
  push:
    branches:
      - feature_actions_dep 
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 437639821200
  # ECR Repository Names
  ECR_CLIENT_REPO: mern/texteditor-client-ga
  ECR_SERVER_REPO: mern/texteditor-server-ga
  # ECS Details
  ECS_SERVICE: task_definition_mern_texteditor-github-actions-service-bq6mprnq # Use your service name
  ECS_CLUSTER: mern-TextEditor-Cluster-GitHubActions # Use your cluster name
  ECS_TASK_DEF_PATH: .aws/task-definition.json
  # Container Names in Task Definition
  CONTAINER_NAME_CLIENT: mern-texteditor-client-container
  CONTAINER_NAME_SERVER: mern-texteditor-server-container

permissions:
  contents: read

jobs:
    setup-env:
      runs-on: ubuntu-latest
      outputs:
        short-sha: ${{ steps.set-sha.outputs.short-sha }}
      steps:
      - name: calculate short sha
        id: set-sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "short-sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Calculated SHORT_SHA: $SHORT_SHA"
   
    build-client:
        needs: setup-env
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Tag, Build and push Client image
          id: build-image-client
          run: |
            SHORT_SHA="${{ needs.setup-env.outputs.short-sha }}"
            FULL_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_CLIENT_REPO}}:${SHORT_SHA}"
            echo "Image pushed to ECR: $FULL_URI"
            
            docker build \
                --build-arg VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL_VALUE }} \
                -t $FULL_URI \
                ./client
            docker push $FULL_URI
            echo "Client Image pushed to ECR: $FULL_URI"
    
    build-server:
        needs: setup-env
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build and push Server image
          id: build-image-server
          run: |
            SHORT_SHA="${{ needs.setup-env.outputs.short-sha }}"
            FULL_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_SERVER_REPO}}:${SHORT_SHA}"
            echo "Image pushed to ECR: $FULL_URI"

            docker build \
                -t $FULL_URI \
                ./server
            docker push $FULL_URI
            echo "Server Image pushed to ECR: $FULL_URI"
    
    deploy:
      needs: [build-server,build-client,setup-env]
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Render Task Definition
        id: render-task-def
        run: |
          CLIENT_IMAGE="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_CLIENT_REPO}}:${{ needs.setup-env.outputs.short-sha }}"
          SERVER_IMAGE="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_SERVER_REPO}}:${{ needs.setup-env.outputs.short-sha }}"
          
          echo "Using Client Image: $CLIENT_IMAGE"          
          echo "Using Server Image: $SERVER_IMAGE"

          # Install jq for JSON processing
          sudo apt-get install jq -y
          
          # Load the template
          TASK_DEF=$(cat ${{ env.ECS_TASK_DEF_PATH }})
          
          # Update Client Image
          TASK_DEF=$(echo "$TASK_DEF" | jq --arg IMAGE "$CLIENT_IMAGE" --arg NAME "$CONTAINER_NAME_CLIENT" \
            '.containerDefinitions[] |= if .name == $NAME then .image = $IMAGE else . end')

          # Update Server Image AND Inject Secrets into Server Environment
          TASK_DEF=$(echo "$TASK_DEF" | jq --arg IMAGE "$SERVER_IMAGE" --arg NAME "$CONTAINER_NAME_SERVER" \
            --arg DB_URL "${{ secrets.DB_URL_VALUE }}" \
            --arg CLIENT_URL "${{ secrets.CLIENT_URL_VALUE }}" \
            --arg JWT_SECRET "${{ secrets.JWT_SECRET_VALUE }}" \
            --arg GEMINI_KEY "${{ secrets.GEMINI_API_KEY_VALUE }}" \
            '.containerDefinitions[] |= if .name == $NAME then 
                .image = $IMAGE | 
                .environment |= map(
                  # Check for all five secrets 
                  if .name == "db_url" then .value = $DB_URL
                  elif .name == "CLIENT_URL" then .value = $CLIENT_URL
                  elif .name == "jwt_secret" then .value = $JWT_SECRET
                  elif .name == "GEMINI_API_KEY" then .value = $GEMINI_KEY
                  else . end
                )
             else . end')
          
          # Write the final task definition to a file
          echo "$TASK_DEF" > task-def-final.json
          echo "task-def-path=task-def-final.json" >> $GITHUB_OUTPUT

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-def-path }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true